name: auto-merge-readme

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'update/')
    # if: github.event.pull_request.user.login == 'eijis-pan'
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{ secrets.EIJIS_GITHUB_TOKEN }}
    steps:
      - name: Checkout repository with preceding commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Approve PR
        run: gh pr review "$PR_URL" --approve

      - name: Enable auto-merge
        run: gh pr merge --merge --auto "$PR_URL"
